### ISSUE TITLE
 cannot import name 'cached_property' from 'werkzeug'

### ISSUE THREAD

**Issue by abdulsamedkayaduman** [postrational/rest_api_demo#17]
Get an error like this don't know what todo. Any idea ?

Traceback (most recent call last):
  File "rest_api_demo/app.py", line 6, in <module>
    from rest_api_demo.api.blog.endpoints.posts import ns as blog_posts_namespace
  File "/home/abdulsamed/temp/rest_api_demo/rest_api_demo/api/blog/endpoints/posts.py", line 4, in <module>
    from flask_restplus import Resource
  File "/home/abdulsamed/.local/share/virtualenvs/rest_api_demo-ypuNYSIq/lib/python3.8/site-packages/flask_restplus/__init__.py", line 4, in <module>
    from . import fields, reqparse, apidoc, inputs, cors
  File "/home/abdulsamed/.local/share/virtualenvs/rest_api_demo-ypuNYSIq/lib/python3.8/site-packages/flask_restplus/fields.py", line 17, in <module>
    from werkzeug import cached_property
ImportError: cannot import name 'cached_property' from 'werkzeug' (/home/abdulsamed/.local/share/virtualenvs/rest_api_demo-ypuNYSIq/lib/python3.8/site-packages/werkzeug/__init__.py)

**Comment by abdulsamedkayaduman** [comment]
My mistake.
